# Generated by Django 3.2.9 on 2021-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedClipboard', '0005_alter_clipboardfile_create_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboardfile',
            name='path',
            field=models.FilePathField(unique=True, verbose_name='Путь до файла относительно BASE_PATH'),
        ),
    ]
