# Generated by Django 3.2.9 on 2021-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedClipboard', '0006_alter_clipboardfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboardfile',
            name='path',
            field=models.CharField(max_length=200, unique=True, verbose_name='Путь до файла относительно BASE_PATH'),
        ),
    ]
