# Generated by Django 3.2.9 on 2021-11-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Название файла')),
                ('type', models.CharField(max_length=32, null=True, verbose_name='Тип файла')),
            ],
        ),
        migrations.CreateModel(
            name='FileBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64, verbose_name='Путь к файлу')),
                ('createDataTime', models.DateTimeField(max_length=64, verbose_name='Дата и время создания файла')),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedClipboard.fileinfo', verbose_name='Необязательная информация о файле')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userbase', verbose_name='Владелец файла')),
            ],
        ),
    ]
