# Generated by Django 3.2.9 on 2021-12-08 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipboardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True, verbose_name='Путь до файла относительно BASE_PATH')),
                ('create_data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания файла')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип файла')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец файла')),
            ],
            options={
                'verbose_name': 'Файл б/о',
                'verbose_name_plural': 'Файлы б/о',
            },
        ),
    ]
