# Generated by Django 3.2.9 on 2021-11-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Имя пользователя')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='Пол пользователя')),
                ('about', models.CharField(max_length=128, null=True, verbose_name='Произвольное описание пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userinfo', verbose_name='Необязательное информация о пользователе')),
            ],
        ),
    ]
